apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "itm.fullname" . }}
  labels:
    {{- include "itm.labels" . | nindent 4 }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "itm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "itm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        env:
          - name: LOCAL_HOST
            value: "{{ .Values.serverIP }}"
          - name: INFLUXDB_PORT
            value: "{{ .Values.influxdbPort }}"
          - name: GRAFANA_PORT
            value: "{{ .Values.grafanaPort }}"
          - name: NAMESPACE
            value: "{{.Release.Namespace}}"
          - name: CLUSTER_API_ADDRESS
            value: "{{ .Values.clusterAPIAddress }}"
          - name: EXTERNAL_ADDRESS
            value: "{{ .Values.externalAddress }}"
        volumeMounts:
        - mountPath: /app/camera_config.json
          name: itm-config
          readOnly: true
          subPath: camera_config.json
      volumes:
      - configMap:
          name: itm-config
        name: itm-config
